Adding Hyas Insight
splunk-soar-connectors/hyasinsight pull request #1
Opened 2022-06-29 09:43 UTC by RamboV

Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

## Pull Request Checklist

#### Please check if your PR fulfills the following requirements:
- [ ] Testing of all the changes has been performed (for bug fixes / features)
- [ ] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [ ] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [ ] Do NOT submit updates to dependencies unless it fixes an issue.
## Pull Request Type

#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

2022-07-07 13:35 UTC, mishalp-crest commented
@RamboV 
Could you please resolve the below two failures:

1. No Code Consts -  Kindly remove `re` module import, the constant file should have constants only
2. Action Names Format - The action names should have lower case and spaces only

2022-07-08 09:39 UTC, RamboV commented
> @RamboV Can you resolve the below two failures?:
> 
> 1. No Code Consts -  Kindly remove `re` module import, the constant file should have constants only
> 2. Action Names Format - The action names should have lower case and spaces only

Hi @mishalp-crest, Thanks, We have made the required changes.

2022-07-13 06:50 UTC, RamboV commented
Hi @mishalp-crest FYI,
we have done the changes for **action_name_lengths** error from Static Test result.

- 'lookup command and control domain' -> 'lookup commandcontrol domain'
- 'lookup command and control email' -> 'lookup commandcontrol email'
- 'lookup command and control hash' -> 'lookup commandcontrol hash'
- 'lookup command and control ip'  -> 'lookup commandcontrol ip' 
- 'lookup mobile geolocation information IP -> 'lookup devicegeo ip

2022-07-18 07:24 UTC, ighelani-crest requested changes

2022-07-18 07:24 UTC, ighelani-crest commented on hyasinsight.json
> +                    "default": "",
Remove unnecessary empty values.

2022-07-18 07:24 UTC, ighelani-crest commented on hyasinsight.json
> +                        "google.com"
Please replace the example values with dummy values, like "example.com"

2022-07-18 07:24 UTC, ighelani-crest commented on hyasinsight.json
> +                        "abuse@godaddy.com"
Use dummy values instead of real names, Check for similar values in all the data paths.

2022-07-18 08:32 UTC, ighelani-crest approved these changes

2022-07-18 16:43 UTC, ricardo-phantom commented on hyasinsight.json
> +                    "description": "Phone to get Lookup Data for Hyas Insight",
Phone number

2022-07-18 16:43 UTC, ricardo-phantom commented on hyasinsight.json
> +                    "description": "Email to get Lookup Data for Hyas Insight",
Email address

2022-07-18 16:55 UTC, jdemelo commented on hyasinsight_connector.py
> +            # Add a dictionary that is made up of the most important values
Should we remove this commented-out code?

2022-07-18 16:58 UTC, jdemelo commented on hyasinsight_connector.py
> +            # Add a dictionary that is made up of the most important values
For lines 724-732, did we mean to include all the comments?

2022-07-18 17:00 UTC, jdemelo commented on hyasinsight_connector.py
> +            # Add a dictionary that is made up of the most important values
Some more commented-out code that is probably not needed

2022-07-18 17:02 UTC, jdemelo commented on hyasinsight_connector.py
> +            # Add a dictionary that is made up of the most important values
Some more commented-out code. Is this needed?

2022-07-18 17:03 UTC, jdemelo commented on hyasinsight_connector.py
> +        if validate_indicator and validate_indicator == "sha256":
I think you may have intended to use `indicator_type` in this comparison instead of the literal.

2022-07-18 17:05 UTC, jdemelo commented on hyasinsight_connector.py
> +            # Add a dictionary that is made up of the most important values
Some more commented-out code. Is this needed?

2022-07-18 17:06 UTC, jdemelo commented on hyasinsight_connector.py
> +            # Add a dictionary that is made up of the most important values
Some more commented-out code. Is this needed?

2022-07-18 19:04 UTC, alexa-phantom commented on hyasinsight_connector.py
> +        endpoint = PASSIVEDNS
Seems like the functions between line 311 and here are all the same style. Maybe a single function with a mapping would work out. This is not a requirement, but a suggestion.

2022-07-18 19:09 UTC, alexa-phantom reviewed
There is a lot of boilerplate code that can be removed. Seems like there can be refactoring done as well to minimize the amount of code in the connector file, especially.

2022-07-19 04:53 UTC, RamboV commented
Hi @mishalp-crest, do you want us to attend these comments from our side?

2022-07-19 07:57 UTC, mishalp-crest commented
> Hi @mishalp-crest, do you want us to attend these comments from our side?

@RamboV Yes Please
We will not be able to verify connector file changes

2022-07-19 12:43 UTC, RamboV commented
Hi, @ricardo-phantom @jdemelo @alexa-phantom, I have attended all the review comments, please review the changes.

2022-07-19 20:19 UTC, alexa-phantom approved these changes

2022-07-19 20:20 UTC, alexa-phantom commented
Updates are good, but will refactors be made further?

2022-07-20 02:15 UTC, ricardo-phantom approved these changes

2022-07-20 04:42 UTC, pdesai-crest commented
Merging this as all review comments are resolved

2022-07-20 04:42 UTC, merged